### ISSUE TITLE
g++は通るがclang++は通らないauto

### ISSUE THREAD

**Issue by dousu** [dousu/MSILM#18]
下記コードでエラーが発生します（clnag++のみ）．
templeate<int I>
const auto get() const -> const decltype(std::get<I>(element)) {return std::get<I>(element);}

**Comment by dousu** [comment]
const autoは注意しようということで違う解決策で回避しました．

**Comment by asciian** [comment]
これは悩ましいですね。const autoは使えると便利なのですが。とりあえず了解しました。
