### ISSUE TITLE
boostの除去

### ISSUE THREAD

**Issue by dousu** [dousu/MSILM#6]
このrepositoryで使われているboostの機能は(少なくともほとんど)C++17の時点で標準化されているため，boostに依存しないコードに書き換えられる．これは，コンパイル時間の短縮や実行環境の簡易化につながるため優先的な課題とする．

**Comment by asciian** [comment]
除去すべきBoostのライブラリリストを提示しておきます。
- [ ] boost_system
- [ ] boost_serialization
- [ ] boost_program_options

**Comment by asciian** [comment]
おめでとうございます！
