### ISSUE TITLE
CIの追加

### ISSUE THREAD

**Issue by asciian** [dousu/MSILM#8]
CIの追加によって、プロジェクトが常にビルドでき実行することができることが保証される。実行できるか否かがダウンロードしてビルドしないと判断できないのは、ユーザーにとって非常に不便であるので追加する必要がある。現状でCIプラットフォームとしての候補は以下の２つである。
- [x] TravisCI
- [ ] CIrcleCI

**Comment by dousu** [comment]
「プロジェクトがビルドできる」を主眼に置いたとき，プルリクエストをマージしたとき動くかどうかもテストしてくれるTravisCIが良いと思われる．
もしCircleCIのメリットが今回の目的に適切であると思う点があるなら教えてください．異論がなければTravisCIですすめましょう．
